// Code generated by MockGen. DO NOT EDIT.
// Source: ./user_balance.go

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"
	port "shop/internal/app/port"

	gomock "github.com/golang/mock/gomock"
)

// MockUserBalanceRepo is a mock of UserBalanceRepo interface.
type MockUserBalanceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserBalanceRepoMockRecorder
}

// MockUserBalanceRepoMockRecorder is the mock recorder for MockUserBalanceRepo.
type MockUserBalanceRepoMockRecorder struct {
	mock *MockUserBalanceRepo
}

// NewMockUserBalanceRepo creates a new mock instance.
func NewMockUserBalanceRepo(ctrl *gomock.Controller) *MockUserBalanceRepo {
	mock := &MockUserBalanceRepo{ctrl: ctrl}
	mock.recorder = &MockUserBalanceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserBalanceRepo) EXPECT() *MockUserBalanceRepoMockRecorder {
	return m.recorder
}

// ChangeUserBalance mocks base method.
func (m *MockUserBalanceRepo) ChangeUserBalance(tx port.Transaction, count int, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserBalance", tx, count, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeUserBalance indicates an expected call of ChangeUserBalance.
func (mr *MockUserBalanceRepoMockRecorder) ChangeUserBalance(tx, count, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserBalance", reflect.TypeOf((*MockUserBalanceRepo)(nil).ChangeUserBalance), tx, count, name)
}

// GetUserBalance mocks base method.
func (m *MockUserBalanceRepo) GetUserBalance(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockUserBalanceRepoMockRecorder) GetUserBalance(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockUserBalanceRepo)(nil).GetUserBalance), ctx, name)
}
